server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        
        # Don't cache index.html
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    # Proxy API requests to the gateway
    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $api_gateway nginx-gateway;
        proxy_pass http://$api_gateway:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
